---
title: "Project Report"
output:
  pdf_document: default
  html: default
date: "2024-04-07"
---

# Project 1 - Project Report

Project 1 for the course COMP4010 - Data Visualization

## Group member

| Name              | Student ID | E-mail                                                               | Title           |
|-------------------|------------|----------------------------------------------------------------------|-----------------|
| Hoang Trung Thanh | V202100516 | [21thanh.ht\@vinuni.edu.vn](mailto:21thanh.ht@vinuni.edu.vn){.email} | Project Manager |
| Tran Tue Nhi      | V202000079 | [20nhi.tt\@vinuni.edu.vn](mailto:20nhi.tt@vinuni.edu.vn){.email}     | Data Analyst    |
| Nguyen Minh Tuan  | V202000254 | [20tuan.nm\@vinuni.edu.vn](mailto:20tuan.nm@vinuni.edu.vn){.email}   | Data Analyst    |

## Introduction

The dataset that we choose is the dataset taken from Our World in Data (OWID). The dataset contains all the important informations about the energy and electric generation/consumption of a country, as well as some important metrics such as GDP, total CO2 emissions, etc. Each row in the table corresponding to a country in a specific year, with the content of the row containing all the information above.

This dataset is important, as it tells the overall picture about the past and current situation of energy and electricity in many countries in the world, which can give us insights about the effect of it on environmental problems such as air pollution, global warming, etc. It can also tells us the development of a country, and the sustainability of such development (is renewable energy in development ? what is the emission per capita ? and so on). One of the big problem with this dataset is the abudance of N/A entries. There are a lot of data missing, and on a variety of columns. As such, it is our job to clean the data and extract all the important available data, as well as fill in the missing data from outside if necessary.
